
import { Report, AuditLog, EMPTY_REPORT_DATA } from './types';

export const FLAGS: Record<string, string> = {
  'India': 'https://flagcdn.com/w320/in.png',
  'Philippines': 'https://flagcdn.com/w320/ph.png',
  'Pakistan': 'https://flagcdn.com/w320/pk.png',
  'Bangladesh': 'https://flagcdn.com/w320/bd.png',
  'UAE': 'https://flagcdn.com/w320/ae.png',
};

export const MOCK_REPORTS: Report[] = [
  {
    id: 'r-101',
    userId: 'u-1',
    title: 'Bilateral Meeting Prep: India',
    status: 'completed',
    updatedAt: '2023-10-24T10:00:00Z',
    data: {
      ...EMPTY_REPORT_DATA,
      reportDate: '2023-11-15',
      country: 'India',
      capital: 'New Delhi',
      officialLanguage: 'Hindi, English',
      population: '1.4B',
      currency: 'Indian Rupee (INR)',
      gdp: '3.5 Trillion USD',
      hdi: '0.633',
      directFlight: true,
      uaeEmbassyLocation: 'New Delhi',
      foreignEmbassyLocation: 'Abu Dhabi',
      crimeRate: 'Low',
      literacyRate: '77.7%',
      governmentType: 'Federal Parliamentary Republic',
      workforceMinistry: 'Ministry of Skill Development',
      uaeWorkforceStats: {
        mohre: {
          totalPrivate: { value: '3,200,000', date: 'Sept 2023' },
          totalDomestic: { value: '800,000', date: 'Sept 2023' },
          byEmirate: [
             { name: 'Abu Dhabi', value: 1200000 },
             { name: 'Dubai', value: 1800000 },
             { name: 'Sharjah', value: 500000 },
             { name: 'Ajman', value: 200000 },
             { name: 'Umm Al Quwain', value: 50000 },
             { name: 'Ras Al Khaimah', value: 150000 },
             { name: 'Fujairah', value: 100000 },
          ],
          bySector: [
            { name: 'Construction', value: 40 },
            { name: 'Retail', value: 20 },
            { name: 'Services', value: 30 }
          ]
        },
        icp: {
          byEmirate: [
             { name: 'Abu Dhabi', value: 1300000 },
             { name: 'Dubai', value: 1900000 },
             { name: 'Sharjah', value: 550000 },
             { name: 'Ajman', value: 210000 },
             { name: 'Umm Al Quwain', value: 55000 },
             { name: 'Ras Al Khaimah', value: 160000 },
             { name: 'Fujairah', value: 110000 },
          ],
          bySector: [
            { name: 'Private', value: 70 },
            { name: 'Government', value: 10 },
            { name: 'Family', value: 20 }
          ]
        },
        custom: [
           { id: 'total-uae', label: 'Total Workers in UAE', value: '5,500,000', date: 'Oct 2023', isTotal: true }
        ]
      },
      averageWage: '$300/month',
      minimumWage: '$60/month',
      workforceStats: {
        totalWorkforce: '580 Million',
        participationMale: 76,
        participationFemale: 24,
        migrationDestinations: [
          { country: 'UAE', count: '3.5 Million' },
          { country: 'USA', count: '2.7 Million' },
          { country: 'Saudi Arabia', count: '2.5 Million' }
        ],
        topSectors: [
          { name: 'Agriculture', value: 45 },
          { name: 'Services', value: 30 },
          { name: 'Industry', value: 25 },
        ],
        availableSkills: ['IT & Software Development', 'Construction', 'Healthcare/Nursing', 'Engineering']
      },
      economicStats: {
        inflation: '5.5%',
        gdp: '3.5 Trillion USD',
        totalExportsToUAE: '30 Billion USD',
        totalImportsFromUAE: '50 Billion USD',
        topExportProducts: ['Petroleum Products', 'Gems & Jewelry', 'Machinery', 'Textiles'],
        topImportProducts: ['Crude Oil', 'Gold', 'Plastics', 'Electronic Goods'],
        mainEconomicPartners: ['USA', 'China', 'UAE', 'Saudi Arabia'],
        tipRank: 'Tier 2',
        remittancesFromUAE: '20 Billion USD (Est. 2023)',
        remittancesGlobal: '125 Billion USD (2023 World Bank)',
        customStats: [
          { id: 'cs-1', label: 'Bilateral Non-Oil Trade', value: '50 Billion USD' }
        ]
      },
      educationStats: {
        topUniversities: ['Indian Institute of Technology Bombay', 'Indian Institute of Science', 'University of Delhi', 'IIT Delhi', 'IIT Madras'],
        primaryEnrollment: '99%',
        higherEducationEnrollment: '27%',
      },
      customSections: [
         { id: 'c-1', title: 'Strategic Partnership Context', content: 'India and UAE share a Comprehensive Economic Partnership Agreement (CEPA) which has significantly boosted non-oil trade.' }
      ],
      recentInteractions: [
         { id: 'ri-1', title: 'Ministerial Visit to New Delhi', date: '2023-05-15', type: 'Visit', details: 'Discussed enhancing labor mobility pathways and skill harmonization standards between NSDC and UAE qualifications.' },
         { id: 'ri-2', title: 'Technical Joint Committee', date: '2023-08-10', type: 'Meeting', details: 'Reviewed implementation of the domestic worker MoU.' },
         { id: 'ri-3', title: 'Phone Call: Ministers', date: '2023-09-01', type: 'Call', details: 'Coordination on upcoming Abu Dhabi Dialogue agenda.' },
         { id: 'ri-4', title: 'Delegation to Abu Dhabi', date: '2023-10-05', type: 'Visit', details: 'High-level delegation visited Tadbeer centers to observe operational standards.' }
      ],
      pointsOfDiscussion: [
         { id: 'pd-1', title: 'Skill Certification', content: 'Harmonization of skill standards between NSDC India and UAE authorities.' },
         { id: 'pd-2', title: 'WPS Integration', content: 'Proposal to integrate Indian e-Migrate system with UAE WPS for better transparency.' },
         { id: 'pd-3', title: 'Cost Reduction', content: 'Strategies to reduce recruitment costs for workers in the blue-collar sector.' }
      ],
      relatedNews: [],
      bilateralAgreements: [
        { title: 'MoU on Manpower', date: '2018-05-12', status: 'Active', summary: 'Framework for domestic worker recruitment protection.' },
        { title: 'Skill Development Partnership', date: '2021-11-20', status: 'Pending', summary: 'Joint certification program for construction workers.' }
      ],
      keyIssues: ['Passport retention complaints', 'Wage protection system compliance in SMEs'],
      recommendations: ['Establish joint committee for grievance redressal', 'Digitize contract validation process'],
      delegations: {
        uae: [
           { id: 'd-uae-1', name: 'H.E. Dr. Abdulrahman Al Awar', title: 'Minister of Human Resources', imageUrl: 'https://ui-avatars.com/api/?name=Abdulrahman+Al+Awar&background=0D8ABC&color=fff', bio: 'Leading the UAE delegation.' }
        ],
        partner: [
           { id: 'd-ind-1', name: 'H.E. Dr. S. Jaishankar', title: 'Minister of External Affairs', imageUrl: 'https://picsum.photos/100/100?random=1', bio: 'Career diplomat and politician serving as the Minister of External Affairs of India.' }
        ]
      }
    }
  }
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  { id: 'l-1', action: 'LOGIN', user: 'Ahmed Al-Mansouri', timestamp: '2023-10-26T08:00:00Z', details: 'Successful login from IP 192.168.1.1' },
  { id: 'l-2', action: 'REPORT_CREATE', user: 'Ahmed Al-Mansouri', timestamp: '2023-10-26T09:15:00Z', details: 'Created draft report for Philippines' },
  { id: 'l-3', action: 'EXPORT_PDF', user: 'Sarah Khan', timestamp: '2023-10-25T16:20:00Z', details: 'Exported India Bilateral Report' },
];

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    reports: 'Reports',
    settings: 'Settings',
    createNew: 'Create Report',
    draft: 'Draft',
    completed: 'Completed',
    logout: 'Logout',
    welcome: 'Welcome back',
    stats: 'Market Statistics',
    step: 'Step',
    next: 'Next',
    back: 'Back',
    save: 'Save Report',
    update: 'Update Report',
    delete: 'Delete Report',
    finish: 'Finish & Preview',
    country: 'Country',
    capital: 'Capital',
    agreements: 'Bilateral Agreements',
    workforce: 'Workforce Distribution',
    delegation: 'Delegation',
    print: 'Print Document',
    printNow: 'Print Now',
    downloadPdf: 'Download PDF',
    close: 'Close',
    closeWindow: 'Close Window',
    confidential: 'CONFIDENTIAL / OFFICIAL USE ONLY',
    ministry: 'Ministry of Human Resources & Emiratisation',
    loginTitle: 'Bilateral Report',
    loginSubtitle: 'Secure Official Access Only',
    reportDetails: 'Report Details',
    reportTitle: 'Report Title',
    reportDate: 'Report Date',
    officialLanguage: 'Official Language',
    population: 'Total Population',
    currency: 'Currency',
    directFlight: 'Direct Flights to UAE',
    flightConnectivity: 'Flight Connectivity',
    yesDirect: 'Yes, Direct Flights Available',
    noDirect: 'Indirect Only',
    toUaeAirports: 'To UAE Airports',
    uaeEmbassy: 'UAE Embassy Location',
    foreignEmbassy: 'Foreign Embassy in UAE',
    gdp: 'GDP',
    hdi: 'HDI',
    fetchData: 'Fetch Data (ILO/WB)',
    fetchEconomy: 'Fetch Economy & Education',
    fetchNews: 'Fetch News (AI)',
    fetchMofa: 'Fetch from MOFA',
    searchOnline: 'Search Online',
    sectionProfile: 'Country Profile',
    sectionUaeWorkforce: 'Workforce in UAE',
    sectionWorkforce: 'Partner Workforce',
    sectionEconomy: 'Economy & Education',
    sectionInteractions: 'Interactions & News',
    sectionAgreements: 'Agreements',
    sectionDelegation: 'Delegations',
    sectionPreview: 'Preview',
    mohreData: 'MOHRE Data',
    icpData: 'ICP Data',
    mohrePrivate: 'MOHRE • Private Sector',
    mohreDomestic: 'MOHRE • Domestic Workers',
    totalPrivate: 'Total Private Sector',
    totalDomestic: 'Total Domestic Workers',
    dataAsOf: 'Data as of',
    workersByEmirate: 'Workers by Emirate (MOHRE)',
    residentsByEmirate: 'Residents by Emirate (ICP)',
    workersBySector: 'Workers by Sector',
    avgWage: 'Avg. Monthly Wage',
    minWage: 'Min. Monthly Wage',
    totalWorkforce: 'Total Workforce',
    maleParticipation: 'Male',
    femaleParticipation: 'Female',
    migrationDestinations: 'Global Migration Destinations',
    availableSkills: 'Skills Availability',
    skillsDisclaimer: 'These skills represent main workforce categories available for external employment.',
    inflation: 'Inflation Rate',
    exportsToUae: 'Exports to UAE',
    importsFromUae: 'Imports from UAE',
    remittances: 'Remittances from UAE',
    globalRemittances: 'Global Remittances Received',
    tipRank: 'TIP Rank',
    tipRankLabel: 'Trafficking in Persons (TIP) Rank',
    topExports: 'Top Export Products to UAE',
    topImports: 'Top Import Products from UAE',
    topTradedCommodities: 'Top Traded Commodities',
    educationInsights: 'Education & Skills',
    primaryEnrollment: 'Primary School Enrollment',
    higherEducationEnrollment: 'Higher Education Enrollment',
    topUniversities: 'Top 5 Universities',
    recentInteractions: 'Relationship Summary',
    recentHighLevelInteractions: 'Relationship Summary',
    pointsDiscussion: 'Points of Discussion',
    relatedNews: 'Related News',
    uaeDelegation: 'UAE Delegation',
    partnerDelegation: 'Partner Delegation',
    ministryOfficials: 'Ministry Officials',
    counterpartOfficials: 'Counterpart Officials',
    addMember: 'Add Member',
    generatedOn: 'Generated on',
    reference: 'REF:',
    date: 'Date',
    securityClass: 'Classification',
    officialRestricted: 'Official / Restricted',
    strategicOverview: 'Strategic Overview',
    economicLandscape: 'Economic Landscape',
    bilateralTrade: 'Trade Statistics',
    subjectMarket: 'Subject Market',
    preparedBy: 'Prepared By',
    intRelationsDept: 'International Relations Dept.',
    reportNotFound: 'Report Not Found',
    reportNotFoundMsg: 'The report you are trying to print could not be found or has been deleted.',
    generatingDoc: 'Generating Ministerial Document...',
    keyDemographics: 'Key Demographics',
    diplomaticMissions: 'Diplomatic Missions',
    notAvailable: 'N/A',
    tradeStats: 'Trade Statistics',
    tradeEducation: 'Trade & Education',
    domesticAnalysis: 'Domestic Labour Market Analysis',
    sourceMarketAnalysis: 'Source Market Analysis',
    relationsDelegations: 'Relations & Delegations',
    bilateralEngagement: 'Bilateral Engagement',
    keyAgreements: 'Key Agreements & MoUs',
    titleProtocol: 'Title / Protocol',
    status: 'Status',
    keyProvisions: 'Key Provisions',
    active: 'Active',
    pending: 'Pending',
    noAgreements: 'No formal agreements recorded.',
    type: 'Type',
    details: 'Details',
    icpDisclaimer: 'ICP figures reflect residency records; MOHRE reflects registered labour relations in the private sector.',
    additionalIndicators: 'Additional Indicators',
    icpHeader: 'Federal Authority for Identity and Citizenship',
    icpSubheader: 'ICP DATA',
    workforceStats: 'Workforce Stats',
    saveReport: 'Save Report',
    crimeRate: 'Crime Rate',
    literacyRate: 'Literacy Rate',
    governmentType: 'Government Type',
    workforceMinistry: 'Ministry of Labour',
    workforceOf: 'Workforce of',
    relationshipSummary: 'Relationship Summary',
    launchWizard: 'Launch Report Wizard',
    destinationCountry: 'Destination Country',
    workerCountEst: 'Worker Count (Est.)',
    sectorDistribution: 'Sector Distribution',
    interactionHelper: 'Record diplomatic visits, key discussion points, and relevant news.',
    reportsDescription: 'Manage and generate bilateral intelligence reports.',
    colReportTitle: 'Report Title',
    colCreatedBy: 'Created By',
    colStatus: 'Status',
    colActions: 'Actions',
    colLastModified: 'Last Modified',
    duplicateReportMsg: 'A report for this country already exists. Please update the existing report. REF:',
    recentReports: 'Recent Reports',
    viewAll: 'View All',
    totalWorkersUaeLabel: 'Total Workers in UAE',
    welcomeMessage: 'Welcome Message',
    edit: 'Edit',
    cancel: 'Cancel',
    lastUpdated: 'Last Updated',
    // Letter Log
    letterLog: 'Letter Log',
    letterLogSubtitle: 'Track strategic correspondence, incoming/outgoing ministerial letters, and their status.',
    addLetter: 'Add New Letter',
    viewLetterLog: 'View Letter Log',
    totalLetters: 'Total Letters Logged',
    closedLetters: 'Closed Letters',
    openLettersCount: 'Open letters',
    internalRef: 'Internal Ref',
    externalRef: 'External Ref',
    topic: 'Subject / Topic',
    open: 'Open',
    closed: 'Closed',
    all: 'All',
    attachment: 'Attachment',
    notes: 'Notes',
    notices: 'Follow-up Notices',
    addNote: 'Add Note',
    deleteLetter: 'Delete Letter',
    priority: 'Priority Label',
    color: 'Label Color',
    personalApiKey: 'Personal API Key',
    letterTitle: 'Letter Title',
  },
  ar: {
    dashboard: 'الصفحة الرئيسة',
    reports: 'التقارير',
    settings: 'الإعدادات',
    createNew: 'إنشاء تقرير',
    draft: 'مسودة',
    completed: 'مكتمل',
    logout: 'تسجيل خروج',
    welcome: 'مرحباً بك',
    stats: 'إحصائيات السوق',
    step: 'خطوة',
    next: 'التالي',
    back: 'سابق',
    save: 'حفظ التقرير',
    update: 'تحديث التقرير',
    delete: 'حذف التقرير',
    finish: 'إنهاء ومعاينة',
    country: 'الدولة',
    capital: 'العاصمة',
    agreements: 'الاتفاقيات الثنائية',
    workforce: 'توزيع القوى العاملة',
    delegation: 'الوفد الرسمي',
    print: 'طباعة التقرير',
    printNow: 'طباعة الآن',
    downloadPdf: 'تحميل التقرير PDF',
    close: 'إغلاق',
    closeWindow: 'إغلاق النافذة',
    confidential: 'سري / للاستخدام الرسمي فقط',
    ministry: 'وزارة الموارد البشرية والتوطين',
    loginTitle: 'تقرير الوضع الحالي للتعاون في مجال القوى العاملة',
    loginSubtitle: 'دخول رسمي آمن فقط',
    reportDetails: 'تفاصيل التقرير',
    reportTitle: 'عنوان التقرير',
    reportDate: 'تاريخ التقرير',
    officialLanguage: 'اللغة الرسمية',
    population: 'إجمالي عدد السكان',
    currency: 'العملة',
    directFlight: 'رحلات مباشرة إلى الإمارات',
    flightConnectivity: 'الربط الجوي',
    yesDirect: 'نعم، تتوفر رحلات مباشرة',
    noDirect: 'رحلات غير مباشرة فقط',
    toUaeAirports: 'إلى مطارات دولة الإمارات',
    uaeEmbassy: 'موقع سفارة الإمارات',
    foreignEmbassy: 'سفارة الدولة الشريكة',
    gdp: 'الناتج المحلي الإجمالي',
    hdi: 'مؤشر التنمية البشرية (HDI)',
    fetchData: 'جلب البيانات (ILO/WB)',
    fetchEconomy: 'جلب البيانات الاقتصادية والتعليمية',
    fetchNews: 'جلب الأخبار (ذكاء اصطناعي)',
    fetchMofa: 'جلب من الخارجية',
    searchOnline: 'بحث عبر الإنترنت',
    sectionProfile: 'الملف التعريفي للدولة',
    sectionUaeWorkforce: 'القوى العاملة في دولة الإمارات',
    sectionWorkforce: 'القوى العاملة لدى الدولة الشريكة',
    sectionEconomy: 'الاقتصاد والتعليم',
    sectionInteractions: 'التفاعلات والأخبار',
    sectionAgreements: 'الاتفاقيات',
    sectionDelegation: 'الوفود',
    sectionPreview: 'معاينة',
    mohreData: 'بيانات الوزارة (MOHRE)',
    icpData: 'بيانات الهيئة (ICP)',
    mohrePrivate: 'وزارة الموارد البشرية والتوطين • القطاع الخاص',
    mohreDomestic: 'وزارة الموارد البشرية والتوطين • العمالة المساعدة',
    totalPrivate: 'إجمالي القطاع الخاص',
    totalDomestic: 'إجمالي العمالة المساعدة',
    dataAsOf: 'البيانات حتى',
    workersByEmirate: 'توزيع العمال حسب الإمارة (MOHRE)',
    residentsByEmirate: 'توزيع المقيمين حسب الإمارة (ICP)',
    workersBySector: 'توزيع العمال حسب القطاع',
    avgWage: 'متوسط الأجر الشهري',
    minWage: 'الحد الأدنى للأجر الشهري',
    totalWorkforce: 'إجمالي القوى العاملة',
    maleParticipation: 'ذكور',
    femaleParticipation: 'إناث',
    migrationDestinations: 'وجهات العمل الرئيسية',
    availableSkills: 'توافر المهارات',
    skillsDisclaimer: 'تمثل هذه المهارات الفئات الرئيسية للعمالة المتاحة للعمل خارجياً بناءً على مخرجات التعليم/التدريب المهني الحالية.',
    inflation: 'معدل التضخم',
    exportsToUae: 'الصادرات إلى الإمارات',
    importsFromUae: 'الواردات من الإمارات',
    remittances: 'التحويلات المالية من الإمارات',
    globalRemittances: 'إجمالي التحويلات العالمية المستلمة',
    tipRank: 'تصنيف الاتجار بالبشر (TIP)',
    tipRankLabel: 'تصنيف الاتجار بالأشخاص (TIP)',
    topExports: 'أهم صادرات الدولة إلى الإمارات',
    topImports: 'أهم واردات الدولة من الإمارات',
    topTradedCommodities: 'أبرز السلع المتبادلة',
    educationInsights: 'التعليم والمهارات',
    primaryEnrollment: 'الالتحاق بالتعليم الابتدائي',
    higherEnrollment: 'الالتحاق بالتعليم العالي',
    topUniversities: 'أفضل 5 جامعات',
    recentInteractions: 'ملخص العلاقة',
    recentHighLevelInteractions: 'ملخص العلاقة',
    pointsDiscussion: 'محاور النقاش',
    relatedNews: 'أخبار ذات صلة',
    uaeDelegation: 'وفد دولة الإمارات',
    partnerDelegation: 'وفد الدولة الشريكة',
    ministryOfficials: 'مسؤولو الوزارة',
    counterpartOfficials: 'المسؤولون النظراء',
    addMember: 'إضافة عضو',
    generatedOn: 'تم الإنشاء بتاريخ',
    reference: 'مرجع:',
    date: 'التاريخ',
    securityClass: 'التصنيف',
    officialRestricted: 'رسمي / مقيّد',
    strategicOverview: 'نظرة استراتيجية عامة',
    economicLandscape: 'المشهد الاقتصادي',
    bilateralTrade: 'إحصاءات التجارة',
    subjectMarket: 'الدولة محل التقرير',
    preparedBy: 'إعداد',
    intRelationsDept: 'إدارة العلاقات الدولية',
    reportNotFound: 'التقرير غير موجود',
    reportNotFoundMsg: 'التقرير الذي تحاول طباعته غير متوفر أو تم حذفه.',
    generatingDoc: 'جارٍ إعداد الوثيقة الوزارية...',
    keyDemographics: 'البيانات السكانية الرئيسية',
    diplomaticMissions: 'البعثات الدبلوماسية',
    notAvailable: 'غير متوفر',
    tradeStats: 'إحصاءات التجارة',
    tradeEducation: 'التجارة والتعليم',
    domesticAnalysis: 'تحليل سوق العمل المحلي',
    sourceMarketAnalysis: 'تحليل سوق المصدر',
    relationsDelegations: 'العلاقات والوفود',
    bilateralEngagement: 'التعاون الثنائي',
    keyAgreements: 'الاتفاقيات ومذكرات التفاهم الرئيسية',
    titleProtocol: 'العنوان / البروتوكول',
    status: 'الحالة',
    keyProvisions: 'أبرز البنود',
    active: 'سارية',
    pending: 'قيد المتابعة',
    noAgreements: 'لا توجد اتفاقيات رسمية مسجلة.',
    type: 'النوع',
    details: 'التفاصيل',
    icpDisclaimer: 'تعكس بيانات ICP سجلات الإقامة، بينما تعكس بيانات MOHRE علاقات العمل المسجلة في القطاع الخاص.',
    additionalIndicators: 'مؤشرات إضافية',
    icpHeader: 'الهيئة الاتحادية للهوية والجنسية',
    icpSubheader: 'بيانات الهيئة الاتحادية للهوية والجنسية',
    workforceStats: 'إحصاءات القوى العاملة',
    saveReport: 'حفظ التقرير',
    crimeRate: 'معدل الجريمة',
    literacyRate: 'معدل الإلمام بالقراءة والكتابة',
    governmentType: 'نظام الحكم',
    workforceMinistry: 'الجهة المعنية بسوق العمل',
    workforceOf: 'القوى العاملة لدى',
    relationshipSummary: 'ملخص العلاقة',
    launchWizard: 'اضغط هنا لإعداد تقرير جديد',
    destinationCountry: 'الدولة',
    workerCountEst: 'عدد العمال',
    sectorDistribution: 'التوزيع على حسب القطاعات',
    interactionHelper: 'اضف معلومات ذات صلة او ملخص العلاقات او محاور النقاش',
    reportsDescription: 'إدارة وإعداد تقارير ثنائية.',
    colReportTitle: 'عنوان التقرير',
    colCreatedBy: 'معد التقرير',
    colStatus: 'حالة التقرير',
    colActions: 'التحكم بالتقرير',
    colLastModified: 'اخر تعديل',
    duplicateReportMsg: 'يوجد تقرير مسبق لهذه الدولة، يرجى تحديث التقرير الموجود. مرجع:',
    recentReports: 'التقارير الحديثة',
    viewAll: 'عرض الكل',
    totalWorkersUaeLabel: 'إجمالي العمالة في الإمارات',
    welcomeMessage: 'رسالة الترحيب',
    edit: 'تعديل',
    cancel: 'إلغاء',
    lastUpdated: 'آخر تحديث',
    // Letter Log
    letterLog: 'سجل المراسلات',
    letterLogSubtitle: 'متابعة المراسلات الاستراتيجية، والرسائل الوزارية الواردة والصادرة، وحالتها.',
    addLetter: 'إضافة مراسلة جديدة',
    viewLetterLog: 'عرض سجل المراسلات',
    totalLetters: 'إجمالي المراسلات المسجلة',
    closedLetters: 'المراسلات المغلقة',
    openLettersCount: 'المراسلات المفتوحة',
    internalRef: 'الرقم المرجعي الداخلي',
    externalRef: 'الرقم المرجعي الخارجي',
    topic: 'الموضوع',
    open: 'مفتوح',
    closed: 'مغلق',
    all: 'الكل',
    attachment: 'المرفق',
    notes: 'الملاحظات',
    notices: 'ملاحظات المتابعة',
    addNote: 'إضافة ملاحظة',
    deleteLetter: 'حذف المراسلة',
    priority: 'تصنيف الأولوية',
    color: 'لون التصنيف',
    personalApiKey: 'مفتاح الـ API الشخصي',
    letterTitle: 'عنوان المراسلة',
  }
};
