
import { Report, AuditLog, EMPTY_REPORT_DATA } from './types';

export const FLAGS: Record<string, string> = {
  'India': 'https://flagcdn.com/w320/in.png',
  'Philippines': 'https://flagcdn.com/w320/ph.png',
  'Pakistan': 'https://flagcdn.com/w320/pk.png',
  'Bangladesh': 'https://flagcdn.com/w320/bd.png',
  'UAE': 'https://flagcdn.com/w320/ae.png',
};

export const MOCK_REPORTS: Report[] = [
  {
    id: 'r-101',
    userId: 'u-1',
    title: 'Bilateral Meeting Prep: India',
    status: 'completed',
    updatedAt: '2023-10-24T10:00:00Z',
    data: {
      ...EMPTY_REPORT_DATA,
      reportDate: '2023-11-15',
      country: 'India',
      capital: 'New Delhi',
      officialLanguage: 'Hindi, English',
      population: '1.4B',
      currency: 'Indian Rupee (INR)',
      gdp: '3.5 Trillion USD',
      hdi: '0.633',
      directFlight: true,
      uaeEmbassyLocation: 'New Delhi',
      foreignEmbassyLocation: 'Abu Dhabi',
      crimeRate: 'Low',
      literacyRate: '77.7%',
      governmentType: 'Federal Parliamentary Republic',
      workforceMinistry: 'Ministry of Skill Development',
      uaeWorkforceStats: {
        mohre: {
          totalPrivate: { value: '3,200,000', date: 'Sept 2023' },
          totalDomestic: { value: '800,000', date: 'Sept 2023' },
          byEmirate: [
             { name: 'Abu Dhabi', value: 1200000 },
             { name: 'Dubai', value: 1800000 },
             { name: 'Sharjah', value: 500000 },
             { name: 'Ajman', value: 200000 },
             { name: 'Umm Al Quwain', value: 50000 },
             { name: 'Ras Al Khaimah', value: 150000 },
             { name: 'Fujairah', value: 100000 },
          ],
          bySector: [
            { name: 'Construction', value: 40 },
            { name: 'Retail', value: 20 },
            { name: 'Services', value: 30 }
          ]
        },
        icp: {
          byEmirate: [
             { name: 'Abu Dhabi', value: 1300000 },
             { name: 'Dubai', value: 1900000 },
             { name: 'Sharjah', value: 550000 },
             { name: 'Ajman', value: 210000 },
             { name: 'Umm Al Quwain', value: 55000 },
             { name: 'Ras Al Khaimah', value: 160000 },
             { name: 'Fujairah', value: 110000 },
          ],
          bySector: [
            { name: 'Private', value: 70 },
            { name: 'Government', value: 10 },
            { name: 'Family', value: 20 }
          ]
        },
        custom: [
           { id: 'total-uae', label: 'Total Workers in UAE', value: '5,500,000', date: 'Oct 2023', isTotal: true }
        ]
      },
      averageWage: '$300/month',
      minimumWage: '$60/month',
      workforceStats: {
        totalWorkforce: '580 Million',
        participationMale: 76,
        participationFemale: 24,
        migrationDestinations: [
          { country: 'UAE', count: '3.5 Million' },
          { country: 'USA', count: '2.7 Million' },
          { country: 'Saudi Arabia', count: '2.5 Million' }
        ],
        topSectors: [
          { name: 'Agriculture', value: 45 },
          { name: 'Services', value: 30 },
          { name: 'Industry', value: 25 },
        ],
        availableSkills: ['IT & Software Development', 'Construction', 'Healthcare/Nursing', 'Engineering']
      },
      economicStats: {
        inflation: '5.5%',
        gdp: '3.5 Trillion USD',
        totalExportsToUAE: '30 Billion USD',
        totalImportsFromUAE: '50 Billion USD',
        topExportProducts: ['Petroleum Products', 'Gems & Jewelry', 'Machinery', 'Textiles'],
        topImportProducts: ['Crude Oil', 'Gold', 'Plastics', 'Electronic Goods'],
        mainEconomicPartners: ['USA', 'China', 'UAE', 'Saudi Arabia'],
        tipRank: 'Tier 2',
        remittancesFromUAE: '20 Billion USD (Est. 2023)',
        remittancesGlobal: '125 Billion USD (2023 World Bank)',
        customStats: [
          { id: 'cs-1', label: 'Bilateral Non-Oil Trade', value: '50 Billion USD' }
        ]
      },
      educationStats: {
        topUniversities: ['Indian Institute of Technology Bombay', 'Indian Institute of Science', 'University of Delhi', 'IIT Delhi', 'IIT Madras'],
        primaryEnrollment: '99%',
        higherEducationEnrollment: '27%',
      },
      customSections: [
         { id: 'c-1', title: 'Strategic Partnership Context', content: 'India and UAE share a Comprehensive Economic Partnership Agreement (CEPA) which has significantly boosted non-oil trade.' }
      ],
      recentInteractions: [
         { id: 'ri-1', title: 'Ministerial Visit to New Delhi', date: '2023-05-15', type: 'Visit', details: 'Discussed enhancing labor mobility pathways and skill harmonization standards between NSDC and UAE qualifications.' },
         { id: 'ri-2', title: 'Technical Joint Committee', date: '2023-08-10', type: 'Meeting', details: 'Reviewed implementation of the domestic worker MoU.' },
         { id: 'ri-3', title: 'Phone Call: Ministers', date: '2023-09-01', type: 'Call', details: 'Coordination on upcoming Abu Dhabi Dialogue agenda.' },
         { id: 'ri-4', title: 'Delegation to Abu Dhabi', date: '2023-10-05', type: 'Visit', details: 'High-level delegation visited Tadbeer centers to observe operational standards.' }
      ],
      pointsOfDiscussion: [
         { id: 'pd-1', title: 'Skill Certification', content: 'Harmonization of skill standards between NSDC India and UAE authorities.' },
         { id: 'pd-2', title: 'WPS Integration', content: 'Proposal to integrate Indian e-Migrate system with UAE WPS for better transparency.' },
         { id: 'pd-3', title: 'Cost Reduction', content: 'Strategies to reduce recruitment costs for workers in the blue-collar sector.' }
      ],
      relatedNews: [],
      bilateralAgreements: [
        { title: 'MoU on Manpower', date: '2018-05-12', status: 'active', summary: 'Framework for domestic worker recruitment protection.' },
        { title: 'Skill Development Partnership', date: '2021-11-20', status: 'pending', summary: 'Joint certification program for construction workers.' }
      ],
      keyIssues: ['Passport retention complaints', 'Wage protection system compliance in SMEs'],
      recommendations: ['Establish joint committee for grievance redressal', 'Digitize contract validation process'],
      delegations: {
        uae: [
           { id: 'd-uae-1', name: 'H.E. Dr. Abdulrahman Al Awar', title: 'Minister of Human Resources', imageUrl: 'https://ui-avatars.com/api/?name=Abdulrahman+Al+Awar&background=0D8ABC&color=fff', bio: 'Leading the UAE delegation.' }
        ],
        partner: [
           { id: 'd-ind-1', name: 'H.E. Dr. S. Jaishankar', title: 'Minister of External Affairs', imageUrl: 'https://picsum.photos/100/100?random=1', bio: 'Career diplomat and politician serving as the Minister of External Affairs of India.' }
        ]
      }
    }
  }
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  { id: 'l-1', action: 'LOGIN', user: 'Ahmed Al-Mansouri', timestamp: '2023-10-26T08:00:00Z', details: 'Successful login from IP 192.168.1.1' },
  { id: 'l-2', action: 'REPORT_CREATE', user: 'Ahmed Al-Mansouri', timestamp: '2023-10-26T09:15:00Z', details: 'Created draft report for Philippines' },
  { id: 'l-3', action: 'EXPORT_PDF', user: 'Sarah Khan', timestamp: '2023-10-25T16:20:00Z', details: 'Exported India Bilateral Report' },
];

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    reports: 'Reports',
    settings: 'Settings',
    createNew: 'Create Report',
    draft: 'Draft',
    completed: 'Completed',
    logout: 'Logout',
    welcome: 'Welcome back',
    stats: 'Market Statistics',
    step: 'Step',
    next: 'Next',
    back: 'Back',
    save: 'Save Report',
    update: 'Update Report',
    delete: 'Delete Report',
    finish: 'Finish & Preview',
    country: 'Country',
    capital: 'Capital',
    agreements: 'Bilateral Agreements',
    workforce: 'Workforce Distribution',
    delegation: 'Delegation',
    print: 'Print Document',
    printNow: 'Print Now',
    downloadPdf: 'Download PDF',
    close: 'Close',
    closeWindow: 'Close Window',
    letterLog: 'Letter Log',
    launchWizard: 'Launch Wizard',
    closedLetters: 'Closed Letters',
    openLettersCount: 'Open Letters',
    viewLetterLog: 'View Letter Log',
    recentReports: 'Recent Reports',
    viewAll: 'View All',
    welcomeMessage: 'Welcome Message',
    edit: 'Edit',
    lastUpdated: 'Last Updated',
    cancel: 'Cancel',
    sectionProfile: 'Country Profile',
    sectionUaeWorkforce: 'Workforce in UAE',
    sectionWorkforce: 'Partner Workforce',
    sectionEconomy: 'Economy & Education',
    sectionInteractions: 'Interactions & News',
    sectionAgreements: 'Agreements',
    sectionDelegation: 'Delegation',
    sectionPreview: 'Preview',
    reportDetails: 'Report Details',
    reportTitle: 'Report Title',
    reportDate: 'Report Date',
    fetchData: 'Fetch Data',
    officialLanguage: 'Official Language',
    population: 'Population',
    currency: 'Currency',
    gdp: 'GDP',
    hdi: 'HDI',
    crimeRate: 'Crime Rate',
    literacyRate: 'Literacy Rate',
    governmentType: 'Government Type',
    workforceMinistry: 'Workforce Ministry',
    mohreData: 'MOHRE Data',
    icpData: 'ICP Data',
    icpDisclaimer: 'Data based on ICP residency records.',
    workersByEmirate: 'Workers by Emirate',
    workersBySector: 'Workers by Sector',
    additionalIndicators: 'Additional Indicators',
    avgWage: 'Average Wage',
    minWage: 'Minimum Wage',
    totalWorkforce: 'Total Workforce',
    maleParticipation: 'Male Participation',
    femaleParticipation: 'Female Participation',
    migrationDestinations: 'Migration Destinations',
    sectorDistribution: 'Sector Distribution',
    inflation: 'Inflation',
    exportsToUae: 'Total Exports to UAE',
    importsFromUae: 'Total Imports from UAE',
    tipRank: 'TIP Rank',
    remittances: 'Remittances (from UAE)',
    topExports: 'Top Export Products',
    topImports: 'Top Import Products',
    primaryEnrollment: 'Primary School Enrollment',
    higherEnrollment: 'Higher Education Enrollment',
    topUniversities: 'Top Universities',
    recentInteractions: 'Recent Interactions',
    pointsOfDiscussion: 'Points of Discussion',
    relatedNews: 'Related News',
    fetchNews: 'Fetch News',
    keyAgreements: 'Key Agreements',
    fetchMofa: 'Fetch Agreements',
    status: 'Status',
    activeLabel: 'Active',
    pendingLabel: 'Pending',
    customLabel: 'Custom',
    customStatusText: 'Custom Status Text',
    uaeDelegation: 'UAE Delegation',
    partnerDelegation: 'Partner Delegation',
    addLetter: 'Add Letter',
    letterTitle: 'Letter Title',
    internalRef: 'Internal Reference',
    externalRef: 'External Reference',
    topic: 'Topic',
    open: 'Open',
    closed: 'Closed',
    priority: 'Priority',
    color: 'Color',
    notes: 'Notes',
    attachment: 'Attachment',
    notices: 'Notices',
    addNote: 'Add Note',
    deleteLetter: 'Delete Letter',
    personalApiKey: 'Personal Gemini API Key',
    // Added missing keys
    reportNotFound: 'Report Not Found',
    reportNotFoundMsg: 'The requested report could not be found or has been deleted.',
    generatingDoc: 'Generating Document...',
    generatedOn: 'Generated on',
    ministry: 'Ministry of Human Resources & Emiratisation',
    loginTitle: 'Bilateral Labour Relations Portal',
    strategicOverview: 'Strategic Overview',
    subjectMarket: 'Subject Market',
    reference: 'Reference',
    date: 'Date',
    securityClass: 'Security Classification',
    officialRestricted: 'Official Restricted',
    keyDemographics: 'Key Demographics',
    economicLandscape: 'Economic Landscape',
    tradeEducation: 'Trade & Education',
    tipRankLabel: 'TIP Rank',
    bilateralTrade: 'Bilateral Trade',
    educationInsights: 'Education Insights',
    domesticAnalysis: 'Domestic Workforce Analysis',
    mohrePrivate: 'MOHRE Private Sector',
    mohreDomestic: 'MOHRE Domestic Workers',
    workforceOf: 'Workforce of',
    sourceMarketAnalysis: 'Source Market Analysis',
    availableSkills: 'Available Skills',
    skillsDisclaimer: '*Data based on regional talent mapping.',
    relationshipSummary: 'Relationship Summary',
    noAgreements: 'No active agreements found.',
    loginSubtitle: 'Ministry of Human Resources & Emiratisation',
    reportsDescription: 'View and manage all bilateral market reports.',
    colReportTitle: 'Report Title',
    colCreatedBy: 'Created By',
    colLastModified: 'Last Modified',
    colStatus: 'Status',
    colActions: 'Actions',
    letterLogSubtitle: 'Manage official correspondence and tracking.',
  },
  ar: {
    dashboard: 'لوحة القيادة',
    reports: 'التقارير',
    settings: 'الإعدادات',
    createNew: 'إنشاء تقرير',
    draft: 'مسودة',
    completed: 'مكتمل',
    logout: 'تسجيل الخروج',
    welcome: 'مرحباً بك مجدداً',
    stats: 'إحصائيات السوق',
    step: 'خطوة',
    next: 'التالي',
    back: 'السابق',
    save: 'حفظ التقرير',
    update: 'تحديث التقرير',
    delete: 'حذف التقرير',
    finish: 'إنهاء ومعاينة',
    country: 'الدولة',
    capital: 'العاصمة',
    agreements: 'الاتفاقيات الثنائية',
    workforce: 'توزيع القوى العاملة',
    delegation: 'الوفد',
    print: 'طباعة المستند',
    printNow: 'اطبع الآن',
    downloadPdf: 'تحميل PDF',
    close: 'إغلاق',
    closeWindow: 'إغلاق النافذة',
    letterLog: 'سجل المراسلات',
    launchWizard: 'بدء المعالج',
    closedLetters: 'المراسلات المغلقة',
    openLettersCount: 'المراسلات المفتوحة',
    viewLetterLog: 'عرض سجل المراسلات',
    recentReports: 'التقارير الأخيرة',
    viewAll: 'عرض الكل',
    welcomeMessage: 'رسالة الترحيب',
    edit: 'تعديل',
    lastUpdated: 'آخر تحديث',
    cancel: 'إلغاء',
    sectionProfile: 'ملف الدولة',
    sectionUaeWorkforce: 'القوى العاملة في الإمارات',
    sectionWorkforce: 'القوى العاملة الشريكة',
    sectionEconomy: 'الاقتصاد والتعليم',
    sectionInteractions: 'التفاعلات والأخبار',
    sectionAgreements: 'الاتفاقيات',
    sectionDelegation: 'الوفود',
    sectionPreview: 'المعاينة',
    reportDetails: 'تفاصيل التقرير',
    reportTitle: 'عنوان التقرير',
    reportDate: 'تاريخ التقرير',
    fetchData: 'جلب البيانات',
    officialLanguage: 'اللغة الرسمية',
    population: 'السكان',
    currency: 'العملة',
    gdp: 'الناتج المحلي الإجمالي',
    hdi: 'مؤشر التنمية البشرية',
    crimeRate: 'معدل الجريمة',
    literacyRate: 'معدل الإلمام بالقراءة والكتابة',
    governmentType: 'نوع الحكومة',
    workforceMinistry: 'وزارة القوى العاملة',
    mohreData: 'بيانات وزارة الموارد البشرية',
    icpData: 'بيانات الهيئة الاتحادية للهوية والجنسية',
    icpDisclaimer: 'البيانات بناءً على سجلات الإقامة.',
    workersByEmirate: 'العاملين حسب الإمارة',
    workersBySector: 'العاملين حسب القطاع',
    additionalIndicators: 'مؤشرات إضافية',
    avgWage: 'متوسط الأجر',
    minWage: 'الحد الأدنى للأجور',
    totalWorkforce: 'إجمالي القوى العاملة',
    maleParticipation: 'مشاركة الذكور',
    femaleParticipation: 'مشاركة الإناث',
    migrationDestinations: 'وجهات الهجرة',
    sectorDistribution: 'توزيع القطاعات',
    inflation: 'التضخم',
    exportsToUae: 'إجمالي الصادرات للإمارات',
    importsFromUae: 'إجمالي الواردات من الإمارات',
    tipRank: 'تصنيف TIP',
    remittances: 'الحوالات (من الإمارات)',
    topExports: 'أهم المنتجات المصدرة',
    topImports: 'أهم المنتجات المستوردة',
    primaryEnrollment: 'الالتحاق بالتعليم الابتدائي',
    higherEnrollment: 'الالتحاق بالتعليم العالي',
    topUniversities: 'أفضل الجامعات',
    recentInteractions: 'التفاعلات الأخيرة',
    pointsOfDiscussion: 'محاور النقاش',
    relatedNews: 'أخبار ذات صلة',
    fetchNews: 'جلب الأخبار',
    keyAgreements: 'الاتفاقيات الرئيسية',
    fetchMofa: 'جلب الاتفاقيات',
    status: 'الحالة',
    activeLabel: 'نشط',
    pendingLabel: 'قيد التنفيذ',
    customLabel: 'مخصص',
    customStatusText: 'نص حالة مخصص',
    uaeDelegation: 'وفد الإمارات',
    partnerDelegation: 'وفد الدولة الشريكة',
    addLetter: 'إضافة مراسلة',
    letterTitle: 'عنوان المراسلة',
    internalRef: 'المرجع الداخلي',
    externalRef: 'المرجع الخارجي',
    topic: 'الموضوع',
    open: 'مفتوح',
    closed: 'مغلق',
    priority: 'الأولوية',
    color: 'اللون',
    notes: 'ملاحظات',
    attachment: 'المرفق',
    notices: 'إشعارات',
    addNote: 'إضافة ملاحظة',
    deleteLetter: 'حذف المراسلة',
    personalApiKey: 'مفتاح Gemini API الشخصي',
    // Added missing keys in Arabic
    reportNotFound: 'التقرير غير موجود',
    reportNotFoundMsg: 'التقرير المطلوب غير موجود أو تم حذفه.',
    generatingDoc: 'جاري إنشاء المستند...',
    generatedOn: 'تم الإنشاء في',
    ministry: 'وزارة الموارد البشرية والتوطين',
    loginTitle: 'بوابة العلاقات العمالية الثنائية',
    strategicOverview: 'نظرة عامة استراتيجية',
    subjectMarket: 'سوق الدولة الشريكة',
    reference: 'المرجع',
    date: 'التاريخ',
    securityClass: 'تصنيف الأمان',
    officialRestricted: 'رسمي محدود',
    keyDemographics: 'الديموغرافيا الرئيسية',
    economicLandscape: 'المشهد الاقتصادي',
    tradeEducation: 'التجارة والتعليم',
    tipRankLabel: 'تصنيف الاتجار',
    bilateralTrade: 'التجارة الثنائية',
    educationInsights: 'رؤى التعليم',
    domesticAnalysis: 'تحليل القوى العاملة المنزلية',
    mohrePrivate: 'قطاع خاص (MOHRE)',
    mohreDomestic: 'عمالة مساعدة (MOHRE)',
    workforceOf: 'القوى العاملة لـ',
    sourceMarketAnalysis: 'تحليل سوق المصدر',
    availableSkills: 'المهارات المتاحة',
    skillsDisclaimer: '*البيانات بناءً على مسح المواهب الإقليمي.',
    relationshipSummary: 'ملخص العلاقة',
    noAgreements: 'لا توجد اتفاقيات نشطة.',
    loginSubtitle: 'وزارة الموارد البشرية والتوطين',
    reportsDescription: 'عرض وإدارة جميع تقارير السوق الثنائية.',
    colReportTitle: 'عنوان التقرير',
    colCreatedBy: 'أنشئ بواسطة',
    colLastModified: 'آخر تعديل',
    colStatus: 'الحالة',
    colActions: 'الإجراءات',
    letterLogSubtitle: 'إدارة المراسلات الرسمية وتتبعها.',
  }
};
